version: '3.8'

services:
  news_agregator:
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - PG_DSN=postgres://admin:admin@pg-local:5432/newsAgregator?sslmode=disable
    networks:
      - mynetwork

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - PG_DSN=postgres://admin:admin@pg-local:5432/newsAgregator?sslmode=disable
    ports:
      - 5432:5432
    networks:
      - mynetwork

networks:
  mynetwork: