version: '3'

volumes:
  postgres_volume:

services:
  pg-local:
    restart: always
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    image: news_agregator
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg-local